"""Scan and copy course directories while excluding upload-unfriendly files."""

from __future__ import annotations

import json
import os
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


DEFAULT_MAX_SIZE_MIB = 95

DEFAULT_EXCLUDED_DIRECTORIES = {
    ".git",
    ".gradle",
    ".hg",
    ".idea",
    ".mypy_cache",
    ".next",
    ".nuxt",
    ".pytest_cache",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pycache__",
    "bin",
    "build",
    "coverage",
    "dist",
    "node_modules",
    "obj",
    "out",
    "target",
    "venv",
}

DEFAULT_EXCLUDED_FILE_NAMES = {
    ".DS_Store",
    "desktop.ini",
    "npm-debug.log",
    "Thumbs.db",
    "yarn-error.log",
}

DEFAULT_EXCLUDED_SUFFIXES = {
    ".class",
    ".dll",
    ".dylib",
    ".ear",
    ".exe",
    ".log",
    ".o",
    ".obj",
    ".pyc",
    ".pyo",
    ".so",
    ".swo",
    ".swp",
    ".tmp",
    ".war",
}


@dataclass(frozen=True)
class CleanRules:
    """Rules used to decide whether a file or directory should be skipped."""

    excluded_directories: frozenset[str] = field(
        default_factory=lambda: normalize_names(DEFAULT_EXCLUDED_DIRECTORIES)
    )
    excluded_file_names: frozenset[str] = field(
        default_factory=lambda: normalize_names(DEFAULT_EXCLUDED_FILE_NAMES)
    )
    excluded_suffixes: frozenset[str] = field(
        default_factory=lambda: normalize_suffixes(DEFAULT_EXCLUDED_SUFFIXES)
    )
    max_size_bytes: int = DEFAULT_MAX_SIZE_MIB * 1024 * 1024

    def with_overrides(
        self,
        *,
        exclude_names: Iterable[str] = (),
        exclude_suffixes: Iterable[str] = (),
        keep_names: Iterable[str] = (),
        max_size_mib: int | None = None,
    ) -> "CleanRules":
        excluded_directories = set(self.excluded_directories)
        excluded_file_names = set(self.excluded_file_names)
        excluded_suffix_set = set(self.excluded_suffixes)

        for name in exclude_names:
            normalized = normalize_name(name)
            excluded_directories.add(normalized)
            excluded_file_names.add(normalized)

        for suffix in exclude_suffixes:
            excluded_suffix_set.add(normalize_suffix(suffix))

        for name in keep_names:
            normalized = normalize_name(name)
            excluded_directories.discard(normalized)
            excluded_file_names.discard(normalized)

        if max_size_mib is None:
            max_size_bytes = self.max_size_bytes
        elif max_size_mib < 0:
            raise ValueError("max size must be zero or greater")
        else:
            max_size_bytes = max_size_mib * 1024 * 1024

        return CleanRules(
            excluded_directories=frozenset(excluded_directories),
            excluded_file_names=frozenset(excluded_file_names),
            excluded_suffixes=frozenset(excluded_suffix_set),
            max_size_bytes=max_size_bytes,
        )


@dataclass
class CleanFinding:
    """One skipped item in a course cleanup report."""

    action: str
    reason: str
    path: str
    size: int = 0


@dataclass
class CleanReport:
    """Report generated by scan or copy mode."""

    mode: str
    source_root: str
    output_root: str | None = None
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )
    findings: list[CleanFinding] = field(default_factory=list)
    reason_counts: dict[str, int] = field(default_factory=dict)
    summary: dict[str, int] = field(
        default_factory=lambda: {
            "directories_seen": 0,
            "directories_skipped": 0,
            "files_seen": 0,
            "files_copied": 0,
            "files_skipped": 0,
            "bytes_seen": 0,
            "bytes_copied": 0,
            "bytes_skipped": 0,
        }
    )

    def add_skip(self, *, action: str, reason: str, path: str, size: int = 0) -> None:
        self.findings.append(CleanFinding(action=action, reason=reason, path=path, size=size))
        self.reason_counts[reason] = self.reason_counts.get(reason, 0) + 1
        if action == "skip_directory":
            self.summary["directories_skipped"] += 1
        else:
            self.summary["files_skipped"] += 1
            self.summary["bytes_skipped"] += size

    def to_dict(self) -> dict[str, Any]:
        return {
            "mode": self.mode,
            "source_root": self.source_root,
            "output_root": self.output_root,
            "generated_at": self.generated_at,
            "summary": self.summary,
            "reason_counts": self.reason_counts,
            "findings": [
                {
                    "action": finding.action,
                    "reason": finding.reason,
                    "path": finding.path,
                    "size": finding.size,
                }
                for finding in self.findings
            ],
        }


def default_rules() -> CleanRules:
    """Return the built-in cleanup rules."""

    return CleanRules()


def scan_tree(input_dir: Path, rules: CleanRules) -> CleanReport:
    """Scan a course directory and report what would be skipped."""

    input_dir = validate_input_dir(input_dir)
    report = CleanReport(mode="scan", source_root=input_dir.name)
    walk_tree(input_dir=input_dir, output_dir=None, rules=rules, report=report)
    return report


def copy_clean_tree(input_dir: Path, output_dir: Path, rules: CleanRules) -> CleanReport:
    """Create a cleaned copy of a course directory."""

    input_dir = validate_input_dir(input_dir)
    output_dir = output_dir.resolve()
    validate_output_dir(input_dir, output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    report = CleanReport(mode="copy", source_root=input_dir.name, output_root=output_dir.name)
    walk_tree(input_dir=input_dir, output_dir=output_dir, rules=rules, report=report)
    return report


def write_reports(report: CleanReport, json_path: Path, markdown_path: Path) -> None:
    """Write JSON and Markdown cleanup reports."""

    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(report.to_dict(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(render_markdown_report(report), encoding="utf-8")


def render_markdown_report(report: CleanReport) -> str:
    """Render a Markdown cleanup report."""

    lines = [
        "# Course Clean Report",
        "",
        f"- Mode: `{report.mode}`",
        f"- Source root: `{report.source_root}`",
        f"- Output root: `{report.output_root or ''}`",
        f"- Generated at: `{report.generated_at}`",
        f"- Directories seen: `{report.summary['directories_seen']}`",
        f"- Directories skipped: `{report.summary['directories_skipped']}`",
        f"- Files seen: `{report.summary['files_seen']}`",
        f"- Files copied: `{report.summary['files_copied']}`",
        f"- Files skipped: `{report.summary['files_skipped']}`",
        f"- Bytes copied: `{report.summary['bytes_copied']}`",
        f"- Bytes skipped: `{report.summary['bytes_skipped']}`",
        "",
    ]
    if report.reason_counts:
        lines.extend(["## Skip Reasons", ""])
        for reason, count in sorted(report.reason_counts.items()):
            lines.append(f"- `{reason}`: `{count}`")
        lines.append("")

    if report.findings:
        lines.extend(["## Skipped Items", ""])
        for finding in report.findings:
            size_text = f" ({finding.size} bytes)" if finding.size else ""
            lines.append(f"- `{finding.action}` `{finding.reason}` `{finding.path}`{size_text}")
    else:
        lines.append("No skipped items.")
    lines.append("")
    return "\n".join(lines)


def walk_tree(
    *,
    input_dir: Path,
    output_dir: Path | None,
    rules: CleanRules,
    report: CleanReport,
) -> None:
    for root, dirs, files in os.walk(input_dir):
        source_root = Path(root)
        relative_dir = source_root.relative_to(input_dir)
        if relative_dir != Path("."):
            report.summary["directories_seen"] += 1

        kept_dirs: list[str] = []
        for dirname in dirs:
            relative_path = relative_dir / dirname
            reason = directory_skip_reason(dirname, rules)
            if reason:
                report.add_skip(
                    action="skip_directory",
                    reason=reason,
                    path=relative_path.as_posix(),
                )
            else:
                kept_dirs.append(dirname)
                if output_dir is not None:
                    (output_dir / relative_path).mkdir(parents=True, exist_ok=True)
        dirs[:] = kept_dirs

        if output_dir is not None:
            (output_dir / relative_dir).mkdir(parents=True, exist_ok=True)

        for filename in files:
            source_file = source_root / filename
            relative_file = source_file.relative_to(input_dir)
            try:
                size = source_file.stat().st_size
            except OSError:
                size = 0

            report.summary["files_seen"] += 1
            report.summary["bytes_seen"] += size

            reason = file_skip_reason(filename, size, rules)
            if reason:
                report.add_skip(
                    action="skip_file",
                    reason=reason,
                    path=relative_file.as_posix(),
                    size=size,
                )
                continue

            if output_dir is not None:
                target = output_dir / relative_file
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source_file, target)
                report.summary["files_copied"] += 1
                report.summary["bytes_copied"] += size


def directory_skip_reason(dirname: str, rules: CleanRules) -> str | None:
    if normalize_name(dirname) in rules.excluded_directories:
        return "excluded_directory"
    return None


def file_skip_reason(filename: str, size: int, rules: CleanRules) -> str | None:
    path = Path(filename)
    if normalize_name(filename) in rules.excluded_file_names:
        return "excluded_file_name"
    if normalize_suffix(path.suffix) in rules.excluded_suffixes:
        return "excluded_suffix"
    if rules.max_size_bytes and size > rules.max_size_bytes:
        return "large_file"
    return None


def validate_input_dir(input_dir: Path) -> Path:
    resolved = input_dir.resolve()
    if not resolved.is_dir():
        raise ValueError(f"input is not a directory: {input_dir}")
    return resolved


def validate_output_dir(input_dir: Path, output_dir: Path) -> None:
    if output_dir == input_dir or output_dir.is_relative_to(input_dir):
        raise ValueError("output directory must not be inside the input directory")
    if output_dir.exists():
        if not output_dir.is_dir():
            raise ValueError(f"output exists and is not a directory: {output_dir}")
        if any(output_dir.iterdir()):
            raise ValueError(f"output directory is not empty: {output_dir}")


def normalize_names(names: Iterable[str]) -> frozenset[str]:
    return frozenset(normalize_name(name) for name in names)


def normalize_name(name: str) -> str:
    return name.casefold()


def normalize_suffixes(suffixes: Iterable[str]) -> frozenset[str]:
    return frozenset(normalize_suffix(suffix) for suffix in suffixes)


def normalize_suffix(suffix: str) -> str:
    if not suffix:
        return suffix
    return suffix.casefold() if suffix.startswith(".") else f".{suffix.casefold()}"
